[package]
edition    = "2021"
name       = "computil"
repository = "https://github.com/LeoLuxo/computil"
version    = "0.1.0"

[features]
default = []

angle    = []
bevy_ecs = []
camera   = ["angle"]
macros   = []
speed    = []
tuples   = []

[dev-dependencies]
approx = "0.5.1"
rstest = "0.21.0"

[dependencies]
bevy_ecs    = "0.13.2"
derive_more = "0.99.17"
mint        = "0.5.9"
paste       = "1.0.14"
vek         = { version = "0.17.0", features = ["bytemuck", "mint", "rgb", "rgba", "serde", "uv", "uvw"] }
