[package]
edition = "2021"
name    = "computil"
version = "0.1.0"

[dev-dependencies]
approx = "0.5.1"
rstest = "0.19.0"

[dependencies]
mint = "0.5.9"
vek  = { version = "0.17.0", features = ["bytemuck", "mint", "rgb", "rgba", "serde", "uv", "uvw"] }
