[package]
edition    = "2021"
name       = "computil"
repository = "https://github.com/LeoLuxo/computil"
version    = "0.1.0"

[dev-dependencies]
approx = "0.5.1"
rstest = "0.19.0"

[dependencies]
mint  = "0.5.9"
paste = "1.0.14"
vek   = { version = "0.17.0", features = ["bytemuck", "mint", "rgb", "rgba", "serde", "uv", "uvw"] }
