[package]
edition = "2021"
name    = "newtype_derive"
version = "0.1.0"

[lib]
name       = "my_proc_macros_lib"
path       = "src/lib.rs"
proc-macro = true

[dependencies]
proc-macro2 = "1.0"
quote       = "1.0"
syn         = { version = "2.0", features = ["extra-traits"] }
